import os

src_files = """
send_pack.cc
"""

install_path = os.environ.get('DVLP_')
print "install path is: " + install_path

libpath = install_path + '/lib'
incpath = install_path + '/include'
incpath_dpdk = install_path + '/include/dpdk'

ccflag_sys = """
-mssse3
"""

dbdp_libs = """
dpdk  
pthread dl
"""

env = Environment(
        CCFLAGS = ['-m64', '-Wall', '--std=c++11', '-g', '-Wl,--no-whole-archive', Split(ccflag_sys)], 
        CPPPATH = [".", incpath, incpath_dpdk], 
        LIBPATH = [libpath],
        LIBS=     ['m', Split(dbdp_libs)]
    )

#'-Wl,--whole-archive'

env.Program(target = 'send_pack', source = Split(src_files))
