import os

src_files = """
send_pack.cc
"""

install_path = os.environ.get('DVLP_')
print "install path is: " + install_path

libpath = install_path + '/lib'
incpath = install_path + 'include'
incpath_dpdk = install_path + 'include/dpdk'

ccflag_sys = """
-MD -MP -D_LINUX -D_UNIX -D_GNU_SOURCE
"""

dbdp_libs = """
rte_eal pthread dl
rte_ethdev rte_mempool 

"""

env = Environment(
        CCFLAGS = ['-m64', '-Wall', '--std=c++11', '-g', '-Wl,--whole-archive', Split(ccflag_sys)], 
        CPPPATH = [".", incpath, incpath_dpdk], 
        LIBPATH = [libpath],
        LIBS=     ['m', Split(dbdp_libs)]
    )

env.Program(target = 'send_pack', source = Split(src_files), variant_dir='debug')


#print "CC is:", env['CC']
